version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: zooportal-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zooportal
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zooportal-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: traxex864/domzverei-backend:latest
    container_name: domzverei-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=zooportal;Username=postgres;Password=postgres
      - App__BaseUrl=https://domzverei.ru
      - App__AdminSecret=supersecretadmin123
    #  - App__FrontendUrl=http://domzverei.ru
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - zooportal-network

  frontend:
    image: traxex864/domzverei-frontend:latest
    container_name: domzverei-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://domzverei.ru/api
      - INTERNAL_API_URL=http://backend:5000/api
    depends_on:
      - backend
    networks:
      - zooportal-network

networks:
  zooportal-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data:
